_target_: controllers.RLAgent
algorithm:
  _target_: stable_baselines3.PPO
  policy: MlpPolicy
  learning_rate: 0.0005
  clip_range: 0.1
  n_steps: 1024
  batch_size: 32
  n_epochs: 10
  gamma: 0.9
training_timesteps: 1e5
desorb_pen: 0