_target_: dac_models.unit_sizing.Detailed
air_velocity: 0.15
geometry:
  unit_volume: 3.75
  void_frac: 0.6
  ri: 0.005
  ro: 0.0051
  l: 0.05
dq_max_cfg:
  k: ${kinetics.k.CO2.ad}
sorbent: ${dac.sorbent}
process_conditions: ${process_conditions}
