_target_: dac_models.unit_sizing.Detailed
dt: ${dt}
process_conditions: ${process_conditions}
v_air: 0.15
P_heater: 5000
geometry:
  unit_volume: 112.5
  void_frac: 0.6
  ri: 0.005
  ro: 0.00505
  l: 0.05
dq_max_cfg:
  _target_: dac_models.unit_sizing.dq_max_first_order
  k: ${kinetics.k.CO2.ad}
sorbent: ${dac.sorbent}
