program: system_simulation.py
project: dac_system
method: grid
name: battery_capacity
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  battery.capacity:
    values: [0, 500, 1000, 1500, 2000, 2500]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}