program: system_simulation.py
project: dac_system
method: grid
name: battery_power
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  battery.power_max:
    values: [0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - sizing=detailed_linear
  - sizing.CO2_per_cycle=6000
  - +naming=[battery.power_max]