program: system_simulation.py
project: dac_system
method: bayes
name: cem_params
metric:
  goal: maximize
  name: CO2_rate_(kg/h)

parameters:

  controller.horizon:
    min: 2
    max: 12

  controller.population_size:
    values: [50, 100, 150, 200, 250, 300]

  controller.alpha:
    min: 0.1
    max: 0.9

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - kinetics=first_order_t90
  - sizing=detailed_first_order
  - controller=cem
  - controller.replan=True
  - +dynamics_model=known_wind
  - +naming=[controller.horizon,controller.population_size,controller.alpha]