program: system_simulation.py
project: dac_system
method: bayes
name: cem_params
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  controller.alpha:
    min: 0.1
    max: 0.3

  controller.elite_frac:
    min: 0.1
    max: 0.3

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - controller=cem
  - +dynamics_model=known_wind
  - +T=48
  - +naming=[controller.alpha,controller.elite_frac]