program: system_simulation.py
project: dac_system
method: grid
name: cem_params
metric:
  goal: maximize
  name: CO2_rate_(kg/h)

parameters:

  controller.horizon:
    values: [6, 8, 10]

  controller.population_size:
    values: [200, 250]

  controller.alpha:
    values: [0.2, 0.4, 0.6]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - kinetics=first_order_t90
  - sizing=detailed_first_order
  - controller=cem
  - controller.replan=True
  - dynamics_model=known_wind