program: system_simulation.py
project: dac_system
method: bayes
name: cem_params
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  controller.population_size:
    values: [150, 200, 250, 300]

  controller.horizon:
    min: 6
    max: 10

  controller.iterations:
    min: 5
    max: 8

  controller.alpha:
    min: 0.1
    max: 0.3

  controller.elite_frac:
    min: 0.1
    max: 0.3

early_terminate:
  type: hyperband
  min_iter: 100
  eta: 2

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +T=1000
  - controller=cem
  - +dynamics_model=constant_wind