program: system_simulation.py
project: dac_system
method: bayes
name: cem_params
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  controller.population_size:
    min: 150
    max: 250

  controller.horizon:
    min: 2
    max: 12

  controller.alpha:
    min: 0.1
    max: 0.5

  controller.iterations:
    min: 3
    max: 8

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - controller=cem
  - +dynamics_model=known_wind