program: system_simulation.py
project: dac_system
method: grid
name: cem_params
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  controller.alpha:
    values: [0.1, 0.2, 0.3]

  controller.elite_frac:
    values: [0.1, 0.2, 0.3]

  controller.replan:
    values: [0, 1]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - controller=cem
  - +dynamics_model=known_wind
  - +T=48