program: system_simulation.py
project: dac_system
method: grid
name: cem_desorb_pen
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  controller.desorb_pen:
    values: [0, 0.2, 0.4, 0.6, 0.8, 1.0]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - controller=cem
  - +dynamics_model=known_wind
  - +naming=[controller.desorb_pen]
  - +T=1000