program: system_simulation.py
project: dac_system
method: grid
name: num_units
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  dac.num_units:
    values: [2, 3, 4, 5, 6, 7, 8]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - sizing=detailed_linear_co2_total
  - +naming=[dac.num_units]