program: system_simulation.py
project: dac_system
method: bayes
name: rule_limits
metric:
  goal: maximize
  name: CO2_rate_(kg/h)

parameters:

  controller.loading_low:
    min: 0.0
    max: 0.5

  controller.loading_high:
    min: 0.5
    max: 1.0

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}