program: system_simulation.py
project: dac_system
method: grid
name: rule_limits
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  controller.loading_low:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]

  controller.loading_high:
    values: [0.5, 0.6, 0.7, 0.8, 0.9]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +naming=[controller.loading_low,controller.loading_high]