program: system_simulation.py
project: dac_system
method: grid
name: unit_sizing
metric:
  goal: maximize
  name: CO2_captured_(kg_h).mean

parameters:

  sizing.CO2_per_cycle:
    values: [1000, 2000, 3000, 4000, 5000]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}