program: system_simulation.py
project: dac_system
method: grid
name: unit_sizing
metric:
  goal: maximize
  name: CO2_rate_(kg/h)

parameters:

  sizing.CO2_per_cycle:
    values: [1000, 2000, 3000, 4000, 5000, 6000]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - kinetics=first_order_t90
  - sizing=detailed_first_order
  - +naming=[sizing.CO2_per_cycle]