_target_: models.sizing.Detailed
dt: ${dt}
process_conditions: ${process_conditions}
sorbent: ${dac.sorbent}
P_heater: 5000
geometry:
  volume: 200
  void_frac: 0.8
  ri: 0.005
  ro: 0.00505
  l: 0.05
dq_max_cfg:
  _target_: models.sizing.dq_max_first_order
  k: ${kinetics.k.CO2.ad_max}
