_target_: models.sizing.Detailed
dt: ${dt}
process_conditions: ${process_conditions}
sorbent: ${dac.sorbent}
time_to_heat: 10
CO2_per_cycle: 3500
contactor: "packed_bed"
geometry:
  void_frac: 0.8
  l: 0.02
dq_max_cfg:
  _target_: models.sizing.dq_max_first_order
  k: ${kinetics.k.CO2.ad_max}
